import "./globals.css";
import Navbar from "./components/Navbar";
import UpperNavbar from"./components/UpperNavbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#e10514]">
        
        <UpperNavbar/>
        
        <Navbar/>
       
        {children}
        </body>
    </html>
  );
}
